name: metrics

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Generate isometric calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          output_action: gist
          committer_gist: 5f7c2f84bf0736d708a619bb92a7df70
          committer_token: ${{ secrets.METRICS_TOKEN }}
          user: VKKKV
